spring:
  datasource:
    url: jdbc:mysql://localhost:3306/menu_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    minimumIdle: 10
    maximumPoolSize: 10
    autoCommit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    enabled: false
    host: localhost
    port: 6379
    timeout: 60000
    database: 0

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, metrics, loggers, caches
